workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mediapro.socialmediamanager
      vars:
        BUNDLE_ID: "com.mediapro.socialmediamanager"
        APP_STORE_APP_ID: "YOUR_APP_STORE_APP_ID"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - amalhusseinmansour@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-workflow:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - mediapro_keystore
      groups:
        - google_play
      vars:
        BUNDLE_ID: "com.socialmedia.social_media_manager"
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - amalhusseinmansour@gmail.com
        notify:
          success: true
          failure: true
