workflows:
  ios-release:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Pod install
        script: cd ios && pod install
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - amalhusseinmansour@gmail.com
